# Generated by Django 3.2.4 on 2021-06-29 10:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210628_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
