# Generated by Django 3.2.4 on 2021-06-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210629_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='updated_on',
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
