# Generated by Django 3.2.4 on 2021-06-29 11:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20210629_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 29, 11, 41, 1, 258335, tzinfo=utc), editable=False),
        ),
    ]
