# Generated by Django 3.2.4 on 2021-07-06 08:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_auctionlisting_created_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='img_url',
            new_name='img',
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.localtime, editable=False),
        ),
    ]
