# Generated by Django 3.2.4 on 2021-07-12 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_rename_starting_bid_bid_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='id',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='title',
        ),
        migrations.AddField(
            model_name='bid',
            name='auctionlisting_ptr',
            field=models.OneToOneField(auto_created=True, default='1', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auctions.auctionlisting'),
            preserve_default=False,
        ),
    ]
