# Generated by Django 3.2.4 on 2021-07-12 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20210712_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='auctionlisting_ptr',
        ),
        migrations.AddField(
            model_name='bid',
            name='id',
            field=models.AutoField(auto_created=True, default='1', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bid',
            name='title',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='auctions.auctionlisting'),
            preserve_default=False,
        ),
    ]
