# Generated by Django 3.2.4 on 2021-07-12 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20210712_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='initial_bid',
            field=models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.CASCADE, related_name='first_bidprice', to='auctions.auctionlisting'),
            preserve_default=False,
        ),
    ]
