# Generated by Django 3.2.4 on 2021-07-12 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_bid_initial_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='initial_bid',
        ),
    ]
