# Generated by Django 3.2.4 on 2021-07-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_auto_20210713_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='listing',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='listing',
            field=models.ManyToManyField(blank=True, related_name='watchlist_for_listing', to='auctions.AuctionListing'),
        ),
    ]
